-- ═══════════════════════════════════════════════════════════════════════════
-- ADS V2 — TABLES
--
-- Run this FIRST, then 02_functions.sql.
-- Everything here is idempotent: running it twice is safe and changes nothing.
--
-- Two groups of tables:
--   INPUT tables  — filled by the ingestion jobs (Meta, ManyChat, GHL, sales sheet).
--   adsv2_* tables — owned by Ads V2 itself. The sync rebuilds them; never hand-edit.
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: Meta ad spend, one row per ad per day.
-- Filled by /api/cron/meta-spend-sync.
-- The reporting_timezone stamp inside raw_payload is load-bearing: Ads V2 only
-- counts rows pulled in America/New_York, so a day means the same thing for
-- every creator no matter what timezone their ad account bills in.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.ads_meta_insights_daily (
  id uuid not null default gen_random_uuid(),
  client_key text not null,
  client_name text not null,
  ad_account_id text not null,
  account_timezone text,
  campaign_id text,
  campaign_name text,
  adset_id text,
  adset_name text,
  ad_id text not null,
  ad_name text,
  keyword_raw text,
  keyword_normalized text,
  date date not null,
  spend_cents integer not null default 0,
  impressions integer not null default 0,
  link_clicks integer not null default 0,
  raw_payload jsonb,
  synced_at timestamptz default now(),
  created_at timestamptz default now(),
  ad_effective_status text,
  ad_configured_status text,
  campaign_effective_status text,
  campaign_configured_status text,
  constraint ads_meta_insights_daily_pkey primary key (id),
  constraint ads_meta_insights_daily_client_key_ad_id_date_key unique (client_key, ad_id, date)
);
create index if not exists idx_ads_meta_insights_client_date on public.ads_meta_insights_daily (client_key, date desc);
create index if not exists idx_ads_meta_insights_ad_date on public.ads_meta_insights_daily (ad_id, date desc);
create index if not exists idx_ads_meta_insights_keyword_date on public.ads_meta_insights_daily (keyword_normalized, date desc);
create index if not exists idx_ads_meta_insights_client_kw_date on public.ads_meta_insights_daily (client_key, keyword_normalized, date desc);
create index if not exists idx_ads_meta_insights_status on public.ads_meta_insights_daily (client_key, ad_effective_status, campaign_effective_status, date desc);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: every keyword DM. This is the canonical record of "someone typed the
-- ad's keyword into the DMs". Filled by the ManyChat webhook.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.ads_keyword_events (
  id uuid not null default gen_random_uuid(),
  source text not null,
  source_event_id text,
  event_type text not null,
  client_key text not null,
  keyword_raw text,
  keyword_normalized text,
  subscriber_id text,
  subscriber_name text,
  setter_name text,
  appointment_id text,
  contact_id text,
  contact_name text,
  value_cents integer,
  event_at timestamptz not null default now(),
  raw_payload jsonb,
  created_at timestamptz default now(),
  constraint ads_keyword_events_pkey primary key (id),
  constraint ads_keyword_events_appointment_id_key unique (appointment_id)
);
create unique index if not exists idx_ads_keyword_events_source_event_id on public.ads_keyword_events (source_event_id) where source_event_id is not null;
create index if not exists idx_ads_keyword_events_keyword_date on public.ads_keyword_events (keyword_normalized, event_at desc);
create index if not exists idx_ads_keyword_events_source_client_date on public.ads_keyword_events (source, client_key, event_at desc);
create index if not exists idx_ads_keyword_events_subscriber_dm on public.ads_keyword_events (subscriber_id) where event_type = 'dm_keyword';
create index if not exists idx_ads_keyword_events_contact_name on public.ads_keyword_events (contact_name);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: booked calls out of GoHighLevel. Filled by the GHL webhook.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.ghl_appointments (
  id bigint generated by default as identity,
  appointment_id text not null,
  calendar_id text,
  calendar_name text,
  contact_id text,
  contact_name text,
  contact_phone text,
  contact_email text,
  start_time timestamptz,
  end_time timestamptz,
  assigned_user_id text,
  closer_name text,
  status text,
  event_type text,
  client text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  keyword_raw text,
  keyword_normalized text,
  raw_payload jsonb,
  constraint ghl_appointments_pkey primary key (id),
  constraint ghl_appointments_appointment_id_key unique (appointment_id)
);
create index if not exists idx_ghl_appointments_start_time on public.ghl_appointments (start_time);
create index if not exists idx_ghl_appointments_closer on public.ghl_appointments (closer_name);
create index if not exists idx_ghl_appointments_start_closer on public.ghl_appointments (start_time, closer_name);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: the sales tracker, one row per call. Money here is ALWAYS USD —
-- it is one team-wide sheet. Never FX-convert it. (Doing so once shaved a
-- $1,200 sale down to $842.) FX applies to ad SPEND only.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.sales_tracker_rows (
  id uuid not null default gen_random_uuid(),
  source text not null default 'google_sheets',
  sheet_id text,
  sheet_tab text,
  sheet_row_key text not null,
  date date not null,
  call_number text,
  prospect_name text not null,
  prospect_name_normalized text,
  call_taken boolean not null default false,
  call_taken_status text,
  call_length text,
  recorded boolean,
  outcome text,
  closer text,
  objection text,
  program_length text,
  contracted_revenue_cents bigint not null default 0,
  collected_revenue_cents bigint not null default 0,
  payment_method text,
  setter text,
  call_notes text,
  recording_link text,
  offer text,
  raw_payload jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  manychat_link text,
  manychat_subscriber_id text,
  constraint sales_tracker_rows_pkey primary key (id),
  constraint sales_tracker_rows_source_sheet_row_key_key unique (source, sheet_row_key)
);
create index if not exists idx_sales_tracker_rows_date on public.sales_tracker_rows (date desc);
create index if not exists idx_sales_tracker_rows_name on public.sales_tracker_rows (prospect_name_normalized);
create index if not exists idx_sales_tracker_rows_outcome on public.sales_tracker_rows (outcome);
create index if not exists idx_sales_tracker_rows_offer on public.sales_tracker_rows (offer);
create index if not exists idx_sales_tracker_rows_manychat_subscriber on public.sales_tracker_rows (manychat_subscriber_id);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: the bridge between a ManyChat subscriber and a GHL contact.
-- Without this a DM and the call it produced are two unrelated people.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.manychat_contact_links (
  id uuid not null default gen_random_uuid(),
  client text not null,
  subscriber_id text not null,
  ghl_contact_id text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint manychat_contact_links_pkey primary key (id),
  constraint manychat_contact_links_client_subscriber_id_key unique (client, subscriber_id)
);
create index if not exists idx_manychat_contact_links_client_subscriber on public.manychat_contact_links (client, subscriber_id);
create index if not exists idx_manychat_contact_links_ghl_contact on public.manychat_contact_links (ghl_contact_id);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: "did this buyer actually come from an ad?" — asked of ManyChat
-- directly, per subscriber. Optional; leave empty and Ads V2 simply has one
-- fewer piece of evidence.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.manychat_origin_checks (
  id uuid not null default gen_random_uuid(),
  client_key text not null,
  subscriber_id text not null,
  prospect_name text,
  sale_date date,
  is_control boolean not null default false,
  from_ad boolean,
  origin_keyword text,
  tags jsonb,
  custom_fields jsonb,
  raw jsonb,
  api_status integer,
  error text,
  checked_at timestamptz not null default now(),
  constraint manychat_origin_checks_pkey primary key (id),
  constraint manychat_origin_checks_client_key_subscriber_id_key unique (client_key, subscriber_id)
);
create index if not exists idx_manychat_origin_checks_sub on public.manychat_origin_checks (subscriber_id);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: keywords used in ORGANIC content, not in paid ads. A sale on one of
-- these is real revenue but not ad revenue, so it is excluded from ROAS.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.organic_keywords (
  id bigint generated by default as identity,
  client_key text not null,
  keyword_normalized text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint organic_keywords_pkey primary key (id),
  constraint organic_keywords_unique unique (client_key, keyword_normalized)
);

-- Same idea, richer: the keyword registry. Ads V2 reads type='organic' from
-- here. Keeping a row in BOTH tables is fine; they agree by construction.
create table if not exists public.registry_keywords (
  keyword_normalized text not null,
  client_key text not null,
  type text not null,
  status text not null,
  first_used date,
  last_used date,
  source_evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint registry_keywords_pkey primary key (keyword_normalized, client_key, type)
);
create index if not exists registry_keywords_lookup_idx on public.registry_keywords (keyword_normalized);
create index if not exists registry_keywords_client_status_idx on public.registry_keywords (client_key, status, type);
-- A live ad keyword is unique across EVERY client, all time. Two creators must
-- never run the same word at once or the DM cannot say whose ad it came from.
create unique index if not exists registry_keywords_active_ad_all_clients_uidx
  on public.registry_keywords (keyword_normalized) where status = 'active' and type = 'ad';

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: the durable copy of each ad's creative (image, video, thumbnail).
-- Meta's own preview URLs expire; these do not.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.ad_creative_image (
  ad_id text not null,
  client_key text,
  source_image_url text,
  stored_image_url text,
  stored_at timestamptz default now(),
  is_video boolean not null default false,
  video_id text,
  stored_video_url text,
  stored_thumb_url text,
  media_synced_at timestamptz,
  media_status text,
  constraint ad_creative_image_pkey primary key (ad_id)
);
create index if not exists ad_creative_image_stored_idx on public.ad_creative_image (ad_id) where stored_image_url is not null;

-- ─────────────────────────────────────────────────────────────────────────
-- OPTIONAL: the identity layer. Ads V2 reads it as one more way to connect a
-- booking to a subscriber. Safe to leave empty — the lookup just misses.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.person_context (
  person_key text not null,
  client_key text,
  display_name text,
  subscriber_ids text[] default '{}'::text[],
  contact_ids text[] default '{}'::text[],
  first_keyword text,
  first_seen_at timestamptz,
  last_activity_at timestamptz,
  dm_in_count integer default 0,
  dm_out_count integer default 0,
  qualified boolean default false,
  booking_readiness_score integer default 0,
  ai_confidence numeric default 0,
  stage_evidence jsonb,
  booked boolean default false,
  taken boolean default false,
  closed boolean default false,
  amount_cents bigint,
  setter_name text,
  closer_name text,
  linked_via text,
  story text,
  updated_at timestamptz default now(),
  constraint person_context_pkey primary key (person_key)
);
create index if not exists idx_person_context_contact_ids on public.person_context using gin (contact_ids);
create index if not exists idx_pc_client on public.person_context (client_key, last_activity_at desc);

-- ─────────────────────────────────────────────────────────────────────────
-- INPUT: daily FX rates. Spend billed in a non-USD ad account is converted at
-- the rate for the day it was spent. Filled by /api/cron/fx-sync.
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.fx_rates (
  rate_date date not null,
  base text not null,
  quote text not null default 'USD',
  rate numeric not null,
  source text not null,
  carried boolean not null default false,
  fetched_at timestamptz not null default now(),
  constraint fx_rates_pkey primary key (rate_date, base, quote)
);
create index if not exists fx_rates_base_quote_date on public.fx_rates (base, quote, rate_date);

-- ═══════════════════════════════════════════════════════════════════════════
-- ADS V2 OWNED TABLES — rebuilt by the sync. Do not hand-edit.
-- ═══════════════════════════════════════════════════════════════════════════

-- Key/value scratchpad. Holds the data_version counter (bumping it invalidates
-- every cached window) and the sync lock that stops two runs overlapping.
create table if not exists public.adsv2_meta (
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  constraint adsv2_meta_pkey primary key (key)
);

-- One row per keyword DM, after attribution has decided what it means.
create table if not exists public.adsv2_dm_facts (
  id uuid not null default gen_random_uuid(),
  event_key text not null,
  client_key text not null,
  subscriber_id text,
  subscriber_name text,
  keyword_normalized text,
  is_organic boolean not null default false,
  awaiting_review boolean not null default false,
  et_day date not null,
  evidence jsonb,
  computed_at timestamptz not null default now(),
  evidence_key text,
  evidence_detail jsonb,
  blank_reason text,
  setter_name text,
  constraint adsv2_dm_facts_pkey primary key (id),
  constraint adsv2_dm_facts_event_key_key unique (event_key)
);
create index if not exists adsv2_dm_client_day_kw on public.adsv2_dm_facts (client_key, et_day, keyword_normalized);
create index if not exists adsv2_dm_client_sub on public.adsv2_dm_facts (client_key, subscriber_id);
create index if not exists dm_facts_setter_idx on public.adsv2_dm_facts (setter_name) where setter_name is not null;
create index if not exists dm_facts_blank_reason_idx on public.adsv2_dm_facts (blank_reason) where blank_reason is not null;

-- One row per booked call.
create table if not exists public.adsv2_booking_facts (
  id uuid not null default gen_random_uuid(),
  appointment_key text not null,
  client_key text not null,
  contact_id text,
  person_name text,
  keyword_normalized text,
  is_organic boolean not null default false,
  awaiting_review boolean not null default false,
  calendar_id text,
  calendar_name text,
  booked_et_day date not null,
  dm_et_day date,
  is_upcoming boolean not null default false,
  status text,
  start_time timestamptz,
  created_time timestamptz,
  evidence jsonb,
  computed_at timestamptz not null default now(),
  taken boolean not null default false,
  evidence_key text,
  evidence_detail jsonb,
  blank_reason text,
  setter_name text,
  linked_subscriber_id text,
  constraint adsv2_booking_facts_pkey primary key (id),
  constraint adsv2_booking_facts_appointment_key_key unique (appointment_key)
);
create index if not exists adsv2_booking_client_day_kw on public.adsv2_booking_facts (client_key, booked_et_day, keyword_normalized);
create index if not exists adsv2_booking_client_contact on public.adsv2_booking_facts (client_key, contact_id);
create index if not exists booking_facts_setter_idx on public.adsv2_booking_facts (setter_name) where setter_name is not null;
create index if not exists booking_facts_blank_reason_idx on public.adsv2_booking_facts (blank_reason) where blank_reason is not null;
create index if not exists idx_adsv2_booking_facts_linked_sub on public.adsv2_booking_facts (linked_subscriber_id) where linked_subscriber_id is not null;

-- One row per sales-tracker row.
create table if not exists public.adsv2_sale_facts (
  id uuid not null default gen_random_uuid(),
  sale_key text not null,
  client_key text,
  keyword_normalized text,
  method text not null default 'none',
  is_organic boolean not null default false,
  awaiting_review boolean not null default false,
  call_taken boolean not null default false,
  is_win boolean not null default false,
  currency text not null default 'USD',
  collected_cents bigint not null default 0,
  contracted_cents bigint not null default 0,
  collected_usd_cents bigint not null default 0,
  contracted_usd_cents bigint not null default 0,
  prospect_name text,
  subscriber_id text,
  closer text,
  sale_et_day date not null,
  evidence jsonb,
  computed_at timestamptz not null default now(),
  evidence_key text,
  evidence_detail jsonb,
  blank_reason text,
  setter_name text,
  call_type text,
  constraint adsv2_sale_facts_pkey primary key (id),
  constraint adsv2_sale_facts_sale_key_key unique (sale_key)
);
create index if not exists adsv2_sale_client_day_kw on public.adsv2_sale_facts (client_key, sale_et_day, keyword_normalized);
create index if not exists adsv2_sale_subscriber on public.adsv2_sale_facts (subscriber_id);
create index if not exists adsv2_sale_facts_win_day_idx on public.adsv2_sale_facts (sale_et_day) where is_win;
create index if not exists sale_facts_blank_reason_idx on public.adsv2_sale_facts (blank_reason) where blank_reason is not null;

-- HUMAN OVERRIDES. A person decided what a machine could not. These outrank
-- every computed answer and survive every rebuild — that is the whole point.
create table if not exists public.adsv2_booking_resolutions (
  appointment_key text not null,
  client_key text not null,
  keyword_normalized text,
  subscriber_id text,
  resolved_by text not null,
  reason text not null,
  created_at timestamptz not null default now(),
  constraint adsv2_booking_resolutions_pkey primary key (appointment_key)
);

create table if not exists public.adsv2_sale_resolutions (
  sale_key text not null,
  client_key text not null,
  keyword_normalized text,
  resolved_by text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint adsv2_sale_resolutions_pkey primary key (sale_key)
);

-- Daily photo of what each campaign/ad set was BUDGETED at. Meta only tells you
-- today's number, so if you don't photograph it daily the history is gone.
create table if not exists public.adsv2_budget_snapshots (
  id uuid not null default gen_random_uuid(),
  client_key text not null,
  entity_level text not null,
  entity_id text not null,
  entity_name text,
  campaign_id text,
  et_day date not null,
  currency text not null default 'USD',
  daily_budget_cents bigint,
  lifetime_budget_cents bigint,
  daily_budget_usd_cents bigint,
  lifetime_budget_usd_cents bigint,
  holds_budget boolean not null default false,
  effective_status text,
  raw jsonb,
  synced_at timestamptz not null default now(),
  constraint adsv2_budget_snapshots_pkey primary key (id),
  constraint adsv2_budget_snapshots_entity_level_entity_id_et_day_key unique (entity_level, entity_id, et_day)
);
create index if not exists adsv2_budget_client_day on public.adsv2_budget_snapshots (client_key, et_day);
create index if not exists adsv2_budget_entity_day on public.adsv2_budget_snapshots (entity_id, et_day);

-- The precomputed answer for one date window, so the page opens instantly.
create table if not exists public.adsv2_window_snapshots (
  id uuid not null default gen_random_uuid(),
  account text not null,
  date_from date not null,
  date_to date not null,
  level text not null,
  status text not null,
  data_version bigint not null,
  payload jsonb not null,
  compute_ms integer,
  computed_at timestamptz not null default now(),
  metrics_payload jsonb,
  constraint adsv2_window_snapshots_pkey primary key (id),
  constraint adsv2_window_snapshots_account_date_from_date_to_level_stat_key unique (account, date_from, date_to, level, status)
);
create index if not exists adsv2_window_lookup on public.adsv2_window_snapshots (account, date_from, date_to, level, status);

-- Every sync attempt, including the ones that were skipped or died.
create table if not exists public.adsv2_sync_runs (
  id uuid not null default gen_random_uuid(),
  source text not null,
  status text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  rows integer,
  duration_ms integer,
  detail jsonb,
  error text,
  constraint adsv2_sync_runs_pkey primary key (id)
);
create index if not exists adsv2_sync_runs_source on public.adsv2_sync_runs (source, started_at desc);

-- Things that went wrong, deduped so one problem is one alert.
create table if not exists public.adsv2_alerts (
  id uuid not null default gen_random_uuid(),
  et_day date not null,
  alert_type text not null,
  client_key text,
  severity text not null default 'warn',
  dedupe_key text not null,
  detail jsonb,
  created_at timestamptz not null default now(),
  constraint adsv2_alerts_pkey primary key (id),
  constraint adsv2_alerts_dedupe_key_key unique (dedupe_key)
);
create index if not exists adsv2_alerts_day_type on public.adsv2_alerts (et_day desc, alert_type);

-- ─────────────────────────────────────────────────────────────────────────
-- Login + sharing
-- ─────────────────────────────────────────────────────────────────────────

-- Who is allowed in. ALLOWED_EMAILS in the env works without this table, so
-- you can sign in before you have added a single row here.
create table if not exists public.app_users (
  id uuid not null default gen_random_uuid(),
  email text not null,
  name text,
  role text default 'user',
  allowed_tabs text[] default array[]::text[],
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint app_users_pkey primary key (id),
  constraint app_users_email_key unique (email)
);

-- Tokenised read-only links so a creator can see their own numbers with no login.
create table if not exists public.public_share_links (
  id uuid not null default gen_random_uuid(),
  token text not null,
  kind text not null default 'ads',
  client_key text,
  label text,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  project_id uuid,
  can_comment boolean not null default false,
  constraint public_share_links_pkey primary key (id),
  constraint public_share_links_token_key unique (token)
);
create index if not exists public_share_links_project_idx on public.public_share_links (project_id) where project_id is not null;

-- ─────────────────────────────────────────────────────────────────────────
-- RLS. Every one of these tables is written and read by the service-role key
-- from server code only, which bypasses RLS. Turning RLS on with no policy is
-- therefore the correct posture: the app keeps working and the anon key —
-- which ships to the browser — can read nothing.
-- ─────────────────────────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'ads_meta_insights_daily','ads_keyword_events','ghl_appointments','sales_tracker_rows',
    'manychat_contact_links','manychat_origin_checks','organic_keywords','registry_keywords',
    'ad_creative_image','person_context','fx_rates','adsv2_meta','adsv2_dm_facts',
    'adsv2_booking_facts','adsv2_sale_facts','adsv2_booking_resolutions','adsv2_sale_resolutions',
    'adsv2_budget_snapshots','adsv2_window_snapshots','adsv2_sync_runs','adsv2_alerts',
    'app_users','public_share_links'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- Seed the version counter so the first sync has something to bump.
insert into public.adsv2_meta (key, value)
values ('data_version', '0'::jsonb)
on conflict (key) do nothing;
